name: Deploy to github pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version:  16.x
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
      - name: Set git config
        run: git config user.name "mavilam" && git config user.email "soyer893@gmail.com"
      - name: Change branch
        run: git checkout --orphan gh-pages
      - name: Build
        run: npm run build
      - name: Commit and push
        run: | 
          git --work-tree dist add --all
          git --work-tree dist commit -m 'Deploy to gh-pages'
          git push origin HEAD:gh-pages --force
      - name: Clean
        run: | 
          rm -r dist
          git checkout -f main
          git branch -D gh-pages
